Update whitepaper.md - Cordeta
neo-tl/docs pull request #3
Opened 2018-02-14 16:12 UTC by cordeta

From Line 1 to 61 A total of 1112 words. (Source codes and variables were not counted)

Thanks

2018-02-14 16:35 UTC, codygee237 reviewed
Your translation: Gayun din
Suggested translation: Gayundin

2018-02-14 20:27 UTC, cordeta commented
Thanks bro ;)

2018-02-14 20:49 UTC, severinolorillajr requested changes

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +​Ang artikulong ito ay iminumungkahi ang isang pinahusay na  Byzantine na toleransiya sa kamalian na algoritmo, na binagay para sa sistemang blockchain. Gayundin, sa sistemang ito, ang mga mensahe ay
*Ang artikulong ito ay nagmumungkahi ng isang pinahusay na (double space) Byzantine

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang blockchain ay isang desentralisadong pagbabahagi ng sistema ng pagtatala. Ito ay pwedeng gamitin sa pagrerehistro o pag-iisyu ng makabagong digital na mga bagay na may halaga, mga sertipikong ika
equity ng stock

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang blockchain ay isang desentralisadong pagbabahagi ng sistema ng pagtatala. Ito ay pwedeng gamitin sa pagrerehistro o pag-iisyu ng makabagong digital na mga bagay na may halaga, mga sertipikong ika
Smart na Kontrata (capitalize)

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang sistemang blockchain ay may kalamangan kesa sa tradisyunal na sentralisadong systema ng pagtatala dahil sa ito'y bukas ,sistemang kailan man ay hindi mababago at may kontra sa maramihang paggasta
bukas ,sistemang to bukas, sistemang

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang sistemang blockchain ay may kalamangan kesa sa tradisyunal na sentralisadong systema ng pagtatala dahil sa ito'y bukas ,sistemang kailan man ay hindi mababago at may kontra sa maramihang paggasta
partid to partido

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Gayunpaman, kayagaya sa ibang sistema ng pagbabahagi, ang mga sistemang blockchain ay hinahamon ng paghinda sa bilis ng network, mga kamalian sa transmisyon, mga softwer bugs, mga butas sa seguridad
softwer to software.
Not all transliterated words are acceptable.

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang mga noda, matapos mamonitor ang pagpapahayag at pagtatanggap ng mga iminumungkahi, ang magpapatunay ng mga transaksyon. Hindi sila pwedeng sumulat ng illegal na transaksyon sa memorya nang sa hul
iminumungkahi to mungkahi

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Ang mga noda, matapos mamonitor ang pagpapahayag at pagtatanggap ng mga iminumungkahi, ang magpapatunay ng mga transaksyon. Hindi sila pwedeng sumulat ng illegal na transaksyon sa memorya nang sa hul
illegal to bawal
text<space>,</space>text to text,</space>test

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Kinakailangan na, sa lahat ng mga noda ng konsensus, at hindi bababa sa  𝑛 − 𝑓 ng mga noda ang nasa orihinal na estado. Ito ay para sabihinna para sa laht ng nodang i, ang taas ng blokeng h and bilan
sabihin na para sa lahat ng

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Kinakailangan na, sa lahat ng mga noda ng konsensus, at hindi bababa sa  𝑛 − 𝑓 ng mga noda ang nasa orihinal na estado. Ito ay para sabihinna para sa laht ng nodang i, ang taas ng blokeng h and bilan
paraang ng  pagsisingkronisa (double space)

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Kinakailangan na, sa lahat ng mga noda ng konsensus, at hindi bababa sa  𝑛 − 𝑓 ng mga noda ang nasa orihinal na estado. Ito ay para sabihinna para sa laht ng nodang i, ang taas ng blokeng h and bilan
hindi  sakop (double space)

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +6) Kahit na anumang noda, matapos matanggap ang buong bloke, ay buburahin ang transaksyon nasa katanungan na galing sa kanyang memorya at magsisimula ng panibagong pag-ikot para sa konsensus;
transaksyong nasa

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +2) Lahat ng mga noda na bookkeeping ay nagmomonitor ng mga datos ng transaksyon na namamahayag ng malaya at itinatago ang mga datos sa kanyang sariling memorya ayon sa pagkakabanggit;
node ng bookkeeping

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Itakda ang mga agwat ng oras ng paggawa ng bloke sa t, sa ilalim ng mga normal na pangyayari, ang algoritmo ay magpapatupad ng sumusunod na pamamaraan：
bloke bilang t

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Lahat ng mga nodang para sa konsensus ay kailangang magpanatili ng talahanayang pang-estado para itala ang kasalukuyang estado ng konsensus. Ang set ng datos na ginamit para sa konsensus mula sa simu
grupo ng datos

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +​Ang ating algoritmo tinitiyak ang segurida at at abilidad na itoy pwedeng gamitin. Dahil sa mga maling noda sa konsensus ng paggawa ng hindi hihigit sa ⌊ (𝑛−1) / 3 ⌋ , ang panksyonalidad at katataga
Ang ating algoritmo ay nagtitiyak sa seguridad at pati na rin sa abilidad na ito'y pwedeng gamitin.

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +​Ang ating algoritmo tinitiyak ang segurida at at abilidad na itoy pwedeng gamitin. Dahil sa mga maling noda sa konsensus ng paggawa ng hindi hihigit sa ⌊ (𝑛−1) / 3 ⌋ , ang panksyonalidad at katataga
*masisigurado to masisiguro

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Itegridad at pagiging tunay ng mga transmisyon ng impormasyon ay natitiyak sa pamamagitan ng kriptograpiya habang ang nagpapadala ay kailangang maglagay ng lagda sa halaga ng hash ng mensaheng pinada
Ang Integridad at Pagpapatunay ng transmisyon ng impormasyon

2018-02-14 20:49 UTC, severinolorillajr commented on tl-tl/node/whitepaper.md
> +Gayunpaman, sa sistemang ito,ang mga mensahe ay sumailalim sa pagkawala, pagkasira, pagkawalang-kilos, at pag-uulit. Ganun din, ang pagkaka-ayos ng pag-papadala ay hindi kailangan na naaalinsunod sa
ito, ang

2018-02-14 20:50 UTC, severinolorillajr commented
@codygee237 , @cordeta 
Please have a thorough review next time as shown on the review that I had just made.
Thanks.

2018-02-15 05:59 UTC, severinolorillajr approved these changes

2018-02-15 06:00 UTC, merged

2018-02-15 06:01 UTC, cordeta commented
I will sir :+1:  indeed a learning process for me too.