Update gui.md
neo-tl/docs pull request #7
Opened 2018-02-16 05:50 UTC by agentzero1

Filipino translation. Ready for review

2018-02-17 19:01 UTC, cordeta requested changes

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +> Maliban kung ito'y nakalagay, ipinakilala ng artikulong ito ang NEO-GUI na tumatakbo sa test net . Para sa karagdagang impormasyon, sumangguni sa [Test Network](testnet.md).
Maliban kung ito ay sinabi, ang artikulong ito ay ipinakikilala ang

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +I-download ang [NEO-GUI](https://neo.org/download) at kunin ang mga file sa isang lokasyon na iyong pinili, pagkatapos ay i-double-click ang neo-gui.exe upang patakbuhin ang kliyente. Kung may anuman
gamitin kagaya ng normal
pagkatapos ay

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +> Ang NEO-GUI client ay tugma sa mga sumusunod na bersyon ng Windows: Windows 7 (Service Pack 1) / Windows 8 / Windows 10.
na kliyente

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +### Pag-synchronize ng blockchain data
Pagsinkronisa

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +### Pag-synchronize ng blockchain data
ng datos ng blockchain

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang kliyente ay dapat na ganap na naka-synchronize bago gamitin. Ang data sa tabi ng "Height" y tumutugma sa taas ng wallet / naka-synchronize na taas ng blockchain / taas na blockchain header. Kapag
nakasinkronisa

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang kliyente ay dapat na ganap na naka-synchronize bago gamitin. Ang data sa tabi ng "Height" y tumutugma sa taas ng wallet / naka-synchronize na taas ng blockchain / taas na blockchain header. Kapag
blockshain(no space)/(no space)taas
*datos
Regular na nag-uupdate ang mga numerong ito.

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Upang mapabilis ang pag-synchronize ng network maaari mong i-download ang isang offline na pakete ng data blockchain hanggang sa isang tiyak na taas ng block. Ang ibig sabihin nito ay kailangan laman
pagsinkronisa 
datos
isink

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Upang magsimula, i-download ang pakete na matatagpuan sa [Client Downloads](https://neo.org/download) na ayon sa iyong network: : chain.acc.zip para sa pangunahing net o  chain.acc.test.zip para s
network:(duplication of ":) chain
net o(double space)chain

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +2. Isara ang neo-gui client at kopyahin chain.acc.zip sa neo-gui folder tulad ng ipinapakita sa figure sa ibaba:
na kliyente at kopyahin ang
na folder
pigura

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +   > Para sa test net package chain.acc.test.zip, kailangan mong palitan ang pangalan ng file sa chain.acc.zip bago ang
pakete ng test net na

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +3. Buksan muli ang neo-gui client, maaari mong makita ang kliyente na ngayon ay naka-synchronize hanggang sa tiyak na punto at ang client ay ipagpapatuloy ang pag-synchronize sa natitirang bahagi ng
kliyente na neo-gui
nakasinkronisa
kliyente
pagsisinkronisa

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Maaari mo ring gamitin ang NEO-CLI command na `export blocks` upang i-export ang naka-synchronize na data ng block sa isang pakete. Para sa karagdagang impormasyon, tingnan ang  [CLI Command Referenc
NEO-CLI na utos na
nakasinkronisang datos ng bloke
tingnan ang(double space)

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang isang wallet na file, kasama ang extension ng json o .db3, nag-iimbak ng sanggunian sa iyong NEO, GAS, at impormasyon ng account sa isang database. Ang file na ito ay napakahalaga at dapat na nak
sanggunian -> reperensiya
nang ligtas

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +> Ang pagkawala ng alinman sa wallet na file o password ng wallet ay magreresulta sa pagkawala ng iyong mga asset. Mangyaring siguraduhin na ang wallet file ay ligtas na nakaimbak at tandaan ang pass
file ng wallet
nakaimbak ->nakatago
use wallet consistently

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +2.I-iklik ang `Browse` upang piliin ang lokasyon ng imbakan ng wallet file, at itakda ang pangalan ng file, at pagkatapos ay i-click ang I-save.
imbakan -> taguan ng file ng wallet
i-save -> Save

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +4. I-klik ang `OK` at ang wallet ay matagumpay na nalikha, na kung saan ang default ay may isang karaniwang account.
ay may kasamang karaniwan na account

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +   >Dahil sa papel ng mekanismo ng pagbabago, ang natitira sa mga asset ay inililipat sa unang address bilang default. Kaya, kailangan ang pag-back up ng kaukulang pribadong key at wallet.
pagbabago na mekanismo
Kinakailangan

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +I-klik ang kanan ng wallet at piliin ang Account -> Tingnan ang Key upang suriin ang impormasyon ng account:
I-right click ang wallet

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +I-klik ang kanan ng wallet at piliin ang Account -> Tingnan ang Key upang suriin ang impormasyon ng account:
(click the right wallet yung unang translation)

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +- Address: Ang katumbas ng isang bank account o numero ng bank card, na ginagamit upang makatanggap ng mga asset sa panahon ng mga transaksyon.
account sa bangko

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +- Private key: Isang random na numero ng 256-bit, itinatago ng gumagamit at hindi kilala sa publiko. Ito ay kumakatawan sa pagmamay-ari ng user account at ang pagmamay-ari ng mga asset sa loob ng acc
Pribadong key
random na 256-bit na numero, tinatago ng 
hindi alam ng publiko 
account ng gumagamit

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +- Public key: Ang bawat pribadong susi ay may katugmang pampublikong susi (Tandaan: Ang pampublikong susi, at ang pribadong susi ng pangunahing impormasyon ay maaaring makita sa pamamagitan ng pag-cl
Pampublikong key
(wag mo na itranslate yung right clicking ng ganyan  , misleading , pagright-click nalang

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +>Hindi dapat ituro ang pribadong susi sa iba. Sa sandaling ibunyag ang pribadong key, maaaring magresulta ito sa pagkawala ng iyong mga ari-arian.
ituro -> ipaalam sa iba
ibunyag -> alam na ng iba

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +>Hindi dapat ituro ang pribadong susi sa iba. Sa sandaling ibunyag ang pribadong key, maaaring magresulta ito sa pagkawala ng iyong mga ari-arian.
translate all assets to mga ari-arian

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +| Function          |Paglalarawan                                        |
punksyon

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +| Lumikha ng Bagong Idadagdag.   | Lumilikha ng bagong address sa wallet                        |
lumilikha - creating
lilika -creates

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +| Angakat           | Import from WIF: Ini-angkat ang katumbas na address sa wallet <br> Mag-angkat mula sa Sertipiko: Ini-angkat ang sertipikasyon <br> Mag-angkat ng Address ng Watch-Only: Matapos m
Angkat (spelling)
Angkat mula sa WIF
Ini-aangkat
watch only, maaari mo nang 
ari-arian

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +#### Mga asset
Ari-arian

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang pag-click sa tab ng `Assets` maaari mong tingnan ang mga asset ng account, kabilang ang Mga Asset (NEO, GAS, mga nilikha ng user na asset), uri, balanse, at ang issuer.
Sa pagclick
`Assets`, maari
ang mga ari-arian na
mga nilikhang ari-arian ng user

2018-02-17 19:01 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang pag-click sa tab ng `Assets` maaari mong tingnan ang mga asset ng account, kabilang ang Mga Asset (NEO, GAS, mga nilikha ng user na asset), uri, balanse, at ang issuer.
taga-isyu

2018-02-17 19:23 UTC, cordeta requested changes

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang pag-click sa tab na `Transaction Record` maaari mong tingnan ang lahat ng mga rekord ng transaksyon na nauugnay sa wallet.
Sa pagclick
`Transaction Record` ay maaari

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Sa bawat oras na muling buksan ang kliyente, kailangan mong i-click ang  `open wallet database` upang piliin kung aling file ng wallet ang bubuksan, tulad ng ipinakita ng larawan:
mabuksan

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +  Mga kliyente na mas mauna kaysa Neo GUI v2.5.2 suporta lamang .db3 file.
ay sumusuporta lamang ng .db3 na file

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +5. Kung magbubukas ng lumang wallet na dd3, kailangan mong piliin kung na-upgrade ang wallet sa bagong format ng NEP-6 ayon sa naipong mensahe.
db3
kailangan mong pumili kung i-upgrade ang wallet
NEP-6 na ayon sa nasabing mensahe

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +   Pagkatapos na ma-upgrade, maibabahagi ang wallet ng NEP-6 sa maraming kliyente, hal. mobile, PC, o Web site. Ngunit hindi ito mabubuksan sa mga kliyente nang mas nauna kaysa sa Neo GUI v2.5.2.
maibabahagi na

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +### Palitan ang password
iba na ang meaning
retain mo nalang as it is

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Maaaring magamit upang baguhin ang password ng pitaka.
use wallet instead of pitaka

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Pagkatapos na baguhin ang password, mangyaring tandaan na i-back up muli ang wallet bilang anumang nakaraang mga pag-backup ng wallet ay hindi maglalaman ng bagong password.
back(no space)up ulit dahil ang mga nakaraang backup ng wallet ay hindi

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Ginagamit ang opsyong ito upang maibalik ang mga error sa client kapag may eksepsiyon. Ang Index ng Wallet ay maaaring kailangang muling itayo sa mga sumusunod na kaso:
kliyente

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Ginagamit ang opsyong ito upang maibalik ang mga error sa client kapag may eksepsiyon. Ang Index ng Wallet ay maaaring kailangang muling itayo sa mga sumusunod na kaso:
muling maitayo

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +- Ang mga asset ng wallet ay nagpapakita ng mga error at hindi tumutugma ang data ng blockchain.
nagpakita

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +- Ang mga asset ng wallet ay nagpapakita ng mga error at hindi tumutugma ang data ng blockchain.
datos

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Tulad ng kasalukuyang block height ay napakatass, muling pagtatayo ng index ng wallet ay maaaring tumagal nang ilang minuto. Mangyaring maging matiyaga.
Dahil napakataas ang bloke, ang muling pagtatayo

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +## Transaksyon
Mga transakyon

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +### Ilipat
Paglipat

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Ilipat ang mga asset sa isang tatanggap na address. Kung ang inilipat na uri ng asset ay equity, ang dalawang partido ay kinakailangang kumpirmahin sa kanilang pirma.
Nililipat ang
kanilang sariling lagda

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +Ilipat ang mga asset sa isang tatanggap na address. Kung ang inilipat na uri ng asset ay equity, ang dalawang partido ay kinakailangang kumpirmahin sa kanilang pirma.
Nililipat ang mga
address ng tatanggap

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +   1. Upang ilipat sa isang solong address, i-klik ang `+` at ipasok ang impormasyon ng paglilipat, hal. uri ng asset, address ng tatanggap, at halaga.
mailipat sa isang

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +   2. Upang ilipat sa isang address ng mga batch, i-klik ang ! ![image](/assets/gui_icon.png) at ipasok ang mga pares ng address at halaga na pinaghihiwalay ng isang puwang, tulad ng ipinapakita sa i
mailipat sa isang grupo

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +   2. Upang ilipat sa isang address ng mga batch, i-klik ang ! ![image](/assets/gui_icon.png) at ipasok ang mga pares ng address at halaga na pinaghihiwalay ng isang puwang, tulad ng ipinapakita sa i
i-klik ang (remove excess "!")

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik ang OK. Kung kailangan, i-klik ![image](/assets/gui_remark.png)  upang ipasok ang impormasyon sa kaugnay na transaksyon na maitatala sa block block ng NEO.
na kaugnay sa

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik ang OK. Kung kailangan, i-klik ![image](/assets/gui_remark.png)  upang ipasok ang impormasyon sa kaugnay na transaksyon na maitatala sa block block ng NEO.
blockchain ng neo 
(remove another block)

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +  Para sa transfer ng pag-aari ng equity, kinakailangan ang mga lagda para sa pagkumpleto ng transaksyon. Kopyahin ang impormasyon ng transaksyon na lumilitaw at ipadala ito sa kabilang panig. Ang ib
pagtransfer ng pag-aari

2018-02-17 19:23 UTC, cordeta commented on tl-tl/node/gui.md
> +  Para sa transfer ng pag-aari ng equity, kinakailangan ang mga lagda para sa pagkumpleto ng transaksyon. Kopyahin ang impormasyon ng transaksyon na lumilitaw at ipadala ito sa kabilang panig. Ang ib
lilitaw at ipdala

2018-02-17 20:59 UTC, severinolorillajr commented
Nice reviews @cordeta , keep it up.
Hope @agentzero1  can also do the same on your PR.
Cheers!

2018-02-18 13:58 UTC, cordeta requested changes
pili ka kung ari-arian or asset sa lahat

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang pag-sign ng impormasyon, ay upang ipahiwatig ang kumpirmasyon ng impormasyon sa pamamagitan ng tagaparka.
Ang Paglalagda ng impormasyon ay nagpapahiwatig ng kumpi.. 
ng impormasyon sa lumagda

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Para sa mga transaksyon na kinasasangkutan ng equity allocation at exchange asset, kinakailangan ang pirma bilang patunay ng pahintulot ng mga partido na kasangkot.
pirma -> lagda
na sangkot.

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +2. Ilagay ang impormasyon ng transaksyon na ipinadala ng ibang partido sa patlang ng input, at pagkatapos ay i-klik ang `sign`. Ang output data ay nabuo.
i-paste ang impormasyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik  `broadcast`. Ang transaksyon ay matagumpay na ipinadala at makukumpleto sa sandaling nakumpirma ng NEO blockchain.
I-klik ang 
nakumpirma na ng

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +### Mga Palitan ng Asset
Palitan ng mga

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang isang online asset exchange sa pagitan ng dalawang partido ay nangangailangan ng parehong partido na mag-sign para sa transaksyon bago ang matagumpay na palitan ng mga asset ay maaaring mangyari.
nangangailangan na ang parehong partido ang lumagda 
bago amangyari ang

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Ang parehong mga partido ay nagsimula ng isang kahilingan sa transaksyon at ipinapadala ang nabuong kahilingan sa bawat isa
Ang parehong partido 
kahilingan na transaction 
at ipadala

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +2. I-verify ang kahilingan na natanggap
Patunayan

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +3. Pagsamahin ang mga kahilingan sa transaksyon mula sa parehong mga partido, bumuo ng mga lagda at ipadala ang mga ito sa bawat isa
kahilingan na

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +4. Mag-sign at i-broadcast ang transaksyon.
Lumagda at ipahayag ang transaksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +#### Hakbang 1 - Pagpapasimula ng isang kahilingan
Unang hakbang

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1. FMula sa NEO-GUI, i-klik ang  `Transaction` -> `Transaction`.
(remove F) Mula sa

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +2.Ilagay ang impormasyon ng account ng iba pang partido at pagkatapos ay i-click ang `+` upang ipasok ang asset upang maipadala.
ilagay ang impormasyon ng ibang account ng partido
i-click or iklik ? Replace all kung ano gagamitin mo 
mapasok ang asset na ipapadala

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik ang `Initiate` upang makabuo ng kahilingan sa transaksyon. Abutin ang kahilingan na lilitaw at ipadala ito sa B. Pagkatapos i-klik ang `Close`.
kahilingan na transaksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> -3. Click `Initiate` to generate the transaction request. Cope the request that appears and send it to B. Then click `Close`.
This should be Copy

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik ang `Initiate` upang makabuo ng kahilingan sa transaksyon. Abutin ang kahilingan na lilitaw at ipadala ito sa B. Pagkatapos i-klik ang `Close`.
kopyahin ang kahilingan

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +4. Ang pahina ng kahilingan ng merge ay ipinapakita. Maghintay ng kahilingan ng transaksyon na ipinadala mula sa B.
pagmemerge

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +4. Ang pahina ng kahilingan ng merge ay ipinapakita. Maghintay ng kahilingan ng transaksyon na ipinadala mula sa B.
kahilingan na transaksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +#### Hakbang 2 - Pagsasama ng kahilingan
Pangalawang hakbang

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Sa pahina ng kahilingan ng merge, i-paste ang kahilingan na ipinadala mula sa B sa patlang ng kahilingan ng counterparty. I-klik ang `Validate`.
pagmemerge

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Sa pahina ng kahilingan ng merge, i-paste ang kahilingan na ipinadala mula sa B sa patlang ng kahilingan ng counterparty. I-klik ang `Validate`.
counterparty -> kabilang partido

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +4.Kopyahin ang signature information at ipadala ito sa B.
impormasyon na lagda

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +#### Hakbang 3 - Pag-sign at pagbro-broadcast ng transaksyon
Pangatlong hakbang
pag-ign at pagpapahayag

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang dalawang panig ay nag-sign at nag-broadcast ng impormasyon sa transaksyon upang makumpleto ang proseso. Para sa karagdagang impormasyon, sumangguni sa [signature](#sign).
panig ay lalagda at magpapahayag

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Upang lumikha ng isang naka-sign na address ng multi-party:
Para makalikha ng nilagdaang address na may maraming partido

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang naka-sign na address ng multi-party ay isang address ng kontrata na nangangailangan ng isa o higit pang mga partido na mag-sign sa panahon ng proseso ng transaksyon.
nilagdaang address na may maraming partido ay isang kontratang address
mag-sign ->lumagda

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +### Pag-claim ng GAS
pagkuha

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
block -> bloke

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
ma-claim -> matanggap

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
tagapagtaguyod -> may hawak

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
magpasimula ng pagtanggap para makuha ang mga GAS

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
bersyon ng PC

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang GAS ay binuo sa bawat bagong block at ilalaan sa address ng mga may hawak ng NEO. (Ang numero sa loob ng mga braket ng balanse ng mga ari-arian ay ang bilang ng GAS na maaaring ma-claim) Sa anuma
functionality -> punksyonalidad

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1.Ilipat ang lahat ng NEO sa loob ng wallet gamit ang isang operasyon sa paglilipat. (Posibleng ipadala ang NEO diretso sa kasalukuyang address) Kapag ang pag-claim para sa GAS ay napagkasunduan, ang
pagtatanggap para sa GAS, 
withdrawn -> ma-withdraw

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Tandaan na ang tampok na ito ay maaari lamang bumuo ng isang application certificate file, ang gumagamit ay kailangan pa ring pumunta sa may-katuturang digital na sertipiko ng sertipiko upang mag-apl
sertipikato ng aplikasyon na file

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Tandaan na ang tampok na ito ay maaari lamang bumuo ng isang application certificate file, ang gumagamit ay kailangan pa ring pumunta sa may-katuturang digital na sertipiko ng sertipiko upang mag-apl
may-katuturang -> kaugnay

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Tandaan na ang tampok na ito ay maaari lamang bumuo ng isang application certificate file, ang gumagamit ay kailangan pa ring pumunta sa may-katuturang digital na sertipiko ng sertipiko upang mag-apl
authority - Awtoridad

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +I-klik ang `Advanced`, `Request certificate`, at punan ang kahilingan ayon sa mga tagubilin na ibinigay.
maga tagabilin -> mga direksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang nakabuo ng file ay magiging tulad ng ipinapakita sa sumusunod na figure:
nakabuo ng -> nabuong file
tulad -> katulad

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +### Pagrehistro ng mga asset
Pagrerehistro ng mga ari-arian

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> -You can create a new asset type in the NEO blockchain, defining the type, name, total amount, and the administrator account of the asset. Currently creating an asset costs 4990 GAS as an additional s
Currently, creating an asset

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Maaari kang lumikha ng isang bagong uri ng asset sa NEO blockchain, pagtukoy sa uri, pangalan, kabuuang halaga, at administrator account ng asset. Sa kasalukuyan ay lumilikha ng isang gastos sa asset
asset -> ari-arian
NEO na blockchain
administrado na account
kasalukuyan, ang paglilikha ng ari-arian ay nagkakahalaga ng 4900 na GAS

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Mayroong dalawang uri ng mga asset, Token at Share. Pagkuha ng mga asset ng Token bilang isang halimbawa, gawin ang mga sumusunod upang lumikha ng asset:
Sa pagkuha

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Mayroong dalawang uri ng mga asset, Token at Share. Pagkuha ng mga asset ng Token bilang isang halimbawa, gawin ang mga sumusunod upang lumikha ng asset:
asset -> ari-arian

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +1. Mula sa NEO-GUI, i-klik ang  `Advanced` -> `Asset Registration`. Tukuyin ang mga sumusunod na pagpipilian at i-klik `OK`：
i-klik ang

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Asset Type:Piliin ang uri ng asset: Token o Ibahagi. Para sa pagbabahagi ng transfer ng pag-aari, kinakailangan ang lagda.
Uri ng ari-arian : Token oh Bahagi.

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Name: The asset name. Ipapakita ito sa pahina ng Asset ng neo-gui at browser ng blockchain pagkatapos maibahagi ang asset.
Pangalan: Pangalan ng asset

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Capped: Suriin ang pagpipiliang ito upang itakda ang pinakamataas na halaga ng ibinibigay na asset.
itong opsyon para matakda ang pinakamalaking halaga ng ari-arian na ibinigay

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Precision: Ang minimum na yunit ng asset. Ang default ay 8, na nagpapahiwatig na ang pinakamaliit na yunit ay 0.00000001. Kung ito ay 0, ang minimum na yunit ay 0.
pinakamaliit na na yunit ng asset

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Precision: Ang minimum na yunit ng asset. Ang default ay 8, na nagpapahiwatig na ang pinakamaliit na yunit ay 0.00000001. Kung ito ay 0, ang minimum na yunit ay 0.
pinakamaliit na yunit

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Owner:Ang issuer ng asset.
May-ari: Ang taga-issue ng mga ari-arian

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Admin: Ang isang administrator ay maaaring baguhin ang pangalan ng asset, ang kabuuang halaga at iba pa. Ang tampok ay hindi pa sinusuportahan.
administrador

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   - Issuer: Ang address ng asset na ipamahagi.
Taga-isssue: 
Ipamamahagi

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang pagpaparehistro ng mga asset ay ipinatutupad sa pamamagitan ng invoking ang smart contract. Sa pahina ng Kontrata ng Inimbitahan, i-klik ang `Test` .
pag-invoke ng mga ontratang smart
pahina ng kontrata ng Invoke

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +  Maaari mo ring i-load ang iyong mga lokal na matalinong mga file ng kontrata.
lokal na kontrang smart na file

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   > Ang pagpaparehistro ng mga ari-arian ay nakukuha ng isang makabuluhang bayad (Sa kasalukuyan ito ay 4990 Gas).
ari-arian ay nanganahulugan ng mahal na bayad

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +4. Kopyahin ang ID ng transaksyon na ibalik at i-paste ito sa Notepad para magamit sa ibang pagkakataon sa pamamahagi ng asset.
ibinalik

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +   > Kinakailangan ng humigit-kumulang 15 minuto upang magparehistro bago ka makakapag-distribute ng mga asset
Inaabot ng humigit
labinlimang

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +3. I-klik ang  `+` upang ipasok ang address ng account at ang halaga ng mga asset na ipamahagi. I-klik ang  `OK`.
ipasok -> mapasok

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Kapag nakumpleto na ang pamamahagi, makikita mo ang mga asset na nilikha ng user ay ipinapakita sa iyong wallet.
na ipinapakita

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +### Mga NEP-5 Asset
Mga ari-arian na NEP-5

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Tinusuportahan ng client ng NEO-GUI ang mga transaksyon ng NEP-5 asset. Upang gumawa ng transaksyon ng asset na NEP-5, kailangan mo munang i-klik ang `Advanced` -> `Options` a client upang magdagdag
Sinusuportahan ng kliyente
ari-arian na NEP-5
ari-arian na NEP-5
transfer -paglilipat at 
at mga transakyon na palitan

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
>  ### Election
Eleksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Ang function na ito ay ginagamit upang magrehistro bilang NEO blockchain validator kandidato.
punksyon
bilang kandidato

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Dapat pansinin na ang halalan ay may malaking halaga. (Ang pangunahing bayad sa network ay 1000 GAS, ang bayad sa network ng pagsubok ay 10 GAS) Mangyaring mag-ingat. Hindi pa available ang function
dapat ay huwag kalimutan na ang eleksyon

2018-02-18 13:58 UTC, cordeta commented on tl-tl/node/gui.md
> +Dapat pansinin na ang halalan ay may malaking halaga. (Ang pangunahing bayad sa network ay 1000 GAS, ang bayad sa network ng pagsubok ay 10 GAS) Mangyaring mag-ingat. Hindi pa available ang function
network na pagsubok

2018-02-19 04:14 UTC, agentzero1 commented
@cordeta  Thank you for review and I'm sorry for not having review your PR . (Babawi na lang ako next time)

2018-02-19 22:53 UTC, Cyyy1998 commented
I update all the problems . Ready for merging

2018-02-19 22:55 UTC, agentzero1 commented
I update all the problems. Ready for merging

2018-02-20 01:04 UTC, merged